Repository codeit-sprint-fullstack/5-sprint-mission-fe, pull requests merged in 2024-12, with the labels that each got.

#19 [김승우] 스프린트 미션 1,2
  README.md
  asset/banner_image.png
  asset/bottom_banner_image.png
  asset/hot_item_image.png
  asset/ic_facebook.png
  asset/ic_instagram.png
  asset/ic_twitter.png
  asset/ic_youtube.png
  asset/login/ic_goggle.png
  asset/login/ic_kakao.png
  asset/login/logo_icon_big.png
  asset/login/logo_name_big.png
  asset/logo_name.png
  asset/panda_icon.png
  asset/register_image.png
  asset/search_image.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signin.html
Labels: 순한맛🐑, 최종 제출

#6 [유호은] sprint1+2
  README.md
  assets/btn_visibility_on.svg
  assets/facebook_icon.png
  assets/google_login_icon.png
  assets/home_bottom_img.png
  assets/home_top_img.png
  assets/hot_item_img.png
  assets/insta_icon.png
  assets/kakao_login_icon.png
  assets/logo_favicon.ico
  assets/logo_img.png
  assets/register_img.png
  assets/search_img.png
  assets/twitter_icon.png
  assets/youtube_icon.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  style.css
  styles/login.css
  styles/reset.css
  styles/signup.css
  styles/style.css
Labels: 매운맛🔥, 최종 제출

#13 [김민희] sprint1+2
  README.md
  faq.html
  img/btn_login_header.png
  img/btn_login_large_active.png
  img/btn_login_large_default.png
  img/btn_signup_large_default.png
  img/btn_visibility_off.png
  img/btn_visit.png
  img/ic_facebook_footer.png
  img/ic_google_login.png
  img/ic_instagram_footer.png
  img/ic_kakao_login.png
  img/ic_twitter_footer.png
  img/ic_youtube_footer.png
  img/logo.png
  img/main_01.png
  img/main_02.png
  img/main_03.png
  img/main_bottom.png
  img/main_welcome.png
  index.html
  items.html
  login.html
  privacy.html
  reset.css
  signup.html
  style.css
Labels: 순한맛🐑, 최종 제출

#8 [이동혁] sprint1+2
  mission01/abc.txt
  mission01/img/Group 19.png
  mission01/img/Img_home_02.png
  mission01/img/Img_home_03.png
  mission01/img/Img_home_bottom.png
  mission01/img/Img_home_top.png
  mission01/img/btn_large.png
  mission01/img/btn_small_48.png
  mission01/img/frame1.png
  mission01/img/ic_facebook.png
  mission01/img/ic_instagram.png
  mission01/img/ic_twitter.png
  mission01/img/ic_youtube.png
  mission01/img/login/Vector.png
  mission01/img/login/ic_facebook.png
  mission01/img/login/logo.png
  mission01/img/panda.ico
  mission01/index.html
  mission01/index_backup.html
  mission01/login.html
  mission01/re-index.html
  mission01/reset.css
  mission01/style not.css
  mission01/style.css
  mission02/img/Component 2.png
  mission02/img/Component 3.png
  mission02/img/Group 19.png
  mission02/img/Img_home_02.png
  mission02/img/Img_home_03.png
  mission02/img/Img_home_bottom.png
  mission02/img/Img_home_top.png
  mission02/img/Vector.png
  mission02/img/Vector2.png
  mission02/img/btn_large.png
  mission02/img/btn_small_48.png
  mission02/img/frame1.png
  mission02/img/ic_facebook.png
  mission02/img/ic_instagram.png
  mission02/img/ic_twitter.png
  mission02/img/ic_youtube.png
  mission02/img/login/Vector.png
  mission02/img/login/ic_facebook.png
  mission02/img/login/logo.png
  mission02/img/logo.png
  mission02/img/panda.ico
  mission02/index.html
  mission02/login.html
  mission02/loginStyle.css
  mission02/mainStyle.css
  mission02/signup.html
Labels: 매운맛🔥, 최종 제출

#23 [김희성] sprint1+2
  Component 2.png
  Component 3.png
  Frame 2609406.png
  Group 33680.png
  Group.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Vector (1).png
  Vector.png
  btn_visibility_on_24px.png
  faq.html
  ic_facebook.png
  index.HTML
  index.css
  items.html
  login.css
  login.html
  privacy.html
  reset.css
  signup.css
  signup.html
  판다 얼굴.png
  판다마켓.png
Labels: 매운맛🔥, 최종 제출

#20 [최은비] sprint1+2
  FAQ.html
  Img_home_01.png
  Img_home_02-1.png
  Img_home_03.png
  Img_home_landing.png
  bottom.png
  cabin.html
  eye-btn.png
  google-icn.png
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  items.html
  kakao-icn.png
  login.html
  loginstyle.css
  logo.png
  logo1.png
  panda.code-workspace
  pandacon.png
  privacy_policy.html
  reset.css
  signup.html
  signupstyle.css
  style.css
Labels: 매운맛🔥, 최종 제출

#18 [윤민호] Sprint1+2
  faq/faq.html
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/img_panda.png
  index.css
  index.html
  item/items.html
  login/img/google.png
  login/img/img_panda.png
  login/img/kakako.png
  login/img/pw-img-on.png
  login/login.css
  login/login.html
  privacy/privacy.html
  reset.css
  signup/img/google.png
  signup/img/img_panda.png
  signup/img/kakako.png
  signup/img/pw-img-on.png
  signup/signup.css
  signup/signup.html
Labels: 매운맛🔥, 최종 제출

#16 [민지영] sprint1+2
  mission01/img/Img_home_bottom.png
  mission01/img/Img_home_landing.png
  mission01/img/Img_hot-item.png
  mission01/img/Img_register.png
  mission01/img/Img_search.png
  mission01/img/ic_facebook.png
  mission01/img/ic_instagram.png
  mission01/img/ic_twitter.png
  mission01/img/ic_youtube.png
  mission01/img/ico.png
  mission01/img/logo.png
  mission01/index.html
  mission01/reset.css
  mission01/style.css
  mission02/css/index-style.css
  mission02/css/reset.css
  mission02/css/style.css
  mission02/html/login.html
  mission02/html/signup.html
  mission02/img/Img_home_bottom.png
  mission02/img/Img_home_landing.png
  mission02/img/Img_hot-item.png
  mission02/img/Img_register.png
  mission02/img/Img_search.png
  mission02/img/btn_visibility_off.png
  mission02/img/google.png
  mission02/img/ic_facebook.png
  mission02/img/ic_instagram.png
  mission02/img/ic_twitter.png
  mission02/img/ic_youtube.png
  mission02/img/ico.png
  mission02/img/kakao.png
  mission02/img/logo.png
  mission02/index.html
Labels: 매운맛🔥, 최종 제출

#9 [정한샘] sprint 1 + 2
  assets/home_01.png
  assets/home_02.png
  assets/home_03.png
  assets/home_bottom.png
  assets/home_top.png
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/logo.png
  assets/logo_goole.png
  assets/logo_kakao.png
  assets/panda_face.png
  assets/title.png
  faq/index.html
  index.html
  login/index.html
  login/style.css
  privacy/index.html
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥, 최종 제출

#11 [김조순] sprint1+2
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/btn_visibility_off_24px.png
  assets/btn_visibility_on_24px.png
  assets/create_item.png
  assets/google_logo_icon.png
  assets/headerIcon.png
  assets/hot_item.png
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/kakao_logo_icon.png
  assets/logo.ico
  assets/logo.png
  assets/search_item.png
  index.html
  js/login.js
  js/main.js
  js/signup.js
  pages/fqa.html
  pages/items.html
  pages/login.html
  pages/main.html
  pages/privacy.html
  pages/signup.html
  style/color.css
  style/login.css
  style/main.css
  style/reset.css
Labels: 매운맛🔥, 최종 제출

#12 [정하윤] sprint1+2
  .DS_Store
  mission01+02.ver2/.DS_Store
  mission01+02.ver2/faq.html
  mission01+02.ver2/image/Img_home_01.png
  mission01+02.ver2/image/Img_home_02.png
  mission01+02.ver2/image/Img_home_03.png
  mission01+02.ver2/image/Img_home_bottom.png
  mission01+02.ver2/image/Img_home_top.png
  mission01+02.ver2/image/btn_visibility_off_24px.png
  mission01+02.ver2/image/btn_visibility_on_24px.png
  mission01+02.ver2/image/favicon.ico
  mission01+02.ver2/image/google.png
  mission01+02.ver2/image/ic_facebook.png
  mission01+02.ver2/image/ic_instagram.png
  mission01+02.ver2/image/ic_twitter.png
  mission01+02.ver2/image/ic_youtube.png
  mission01+02.ver2/image/kakao.png
  mission01+02.ver2/image/logo.png
  mission01+02.ver2/image/logo_pandamarket.png
  mission01+02.ver2/index.html
  mission01+02.ver2/items.html
  mission01+02.ver2/login.css
  mission01+02.ver2/login.html
  mission01+02.ver2/privacy.html
  mission01+02.ver2/reset.css
  mission01+02.ver2/signup.css
  mission01+02.ver2/signup.html
  mission01+02.ver2/style.css
Labels: 매운맛🔥, 최종 제출

#17 [최수빈] sprint 1+2
  .DS_Store
  FAQ.html
  img/.DS_Store
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom-1.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/google.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakaotalk.png
  img/logo.png
  index.html
  items.html
  login.html
  login_style.css
  privacy.html
  reset.css
  signup.html
  singup_style.css
  style.css
Labels: 순한맛🐑, 최종 제출

#22 [신진호] Sprint1+2
  .idea/.gitignore
  .idea/5-sprint-mission-fe.iml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  colorpal.css
  faq/faq.html
  imgs/Img_home_01.png
  imgs/Img_home_02.png
  imgs/Img_home_03.png
  imgs/Img_home_bottom.png
  imgs/Img_home_top.png
  imgs/btn_visibility_on_24px.png
  imgs/google-circle.png
  imgs/ic_facebook.png
  imgs/ic_instagram.png
  imgs/ic_twitter.png
  imgs/ic_youtube.png
  imgs/kakao-circle.png
  imgs/logo-big.png
  imgs/logo-small.png
  index.html
  items/items.html
  login/login.css
  login/login.html
  privacy/privacy.html
  signup/signup.css
  signup/signup.html
  style.css
Labels: 매운맛🔥, 최종 제출

#24 [최유리] sprint1+2
  faq.html
  image/Group (1).png
  image/Group 19.png
  image/Group.png
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/Vector (1).png
  image/Vector.png
  image/btn_visibility_off_24px.png
  image/google.png
  image/kakao.png
  index.html
  items.html
  login.html
  privacy.html
  reset.css
  signup.html
  style.css
Labels: 매운맛🔥, 미완성🫠

#10 [봉재완] sprint 1+2
  mission1+2/Panda.css
  mission1+2/img/Component 2.png
  mission1+2/img/Component 3.png
  mission1+2/img/Frame 2608833.png
  mission1+2/img/Img_home_02.png
  mission1+2/img/Img_home_03.png
  mission1+2/img/Img_home_bottom.png
  mission1+2/img/Img_home_top.png
  mission1+2/img/Vector.png
  mission1+2/img/ic_facebook.png
  mission1+2/img/ic_instagram.png
  mission1+2/img/ic_twitter.png
  mission1+2/img/ic_youtube.png
  mission1+2/img/login-logo.png
  mission1+2/img/logo.png
  mission1+2/index.html
  mission1+2/items.html
  mission1+2/login/index.html
  mission1+2/login/style.css
  mission1+2/signup/index.html
  mission1+2/signup/style.css
Labels: 매운맛🔥, 최종 제출
