Repository codeit-sprint-fullstack/5-sprint-mission-fe, pull requests merged in 2025-03, with the labels that each got.

#115 [윤민호] sprint8
  .gitignore
  README.md
  components/bulletinBoardAll.tsx
  components/bulletinBoardBest.tsx
  components/footer.tsx
  components/head.tsx
  next.config.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/bulletinBoardApi.ts
  pages/api/commentApi.ts
  pages/bulletin-board/index.tsx
  pages/edit/[id].tsx
  pages/index.tsx
  pages/write/index.tsx
  public/assets/Img_home_01.svg
  public/assets/Img_home_02.svg
  public/assets/Img_home_03.svg
  public/assets/Img_home_bottom.svg
  public/assets/basic_img.svg
  public/assets/default_img.svg
  public/assets/header-panda.svg
  public/assets/ic_arrow_down.svg
  public/assets/ic_facebook.svg
  public/assets/ic_heart.svg
  public/assets/ic_instagram.svg
  public/assets/ic_search.svg
  public/assets/ic_twitter.svg
  public/assets/ic_youtube.svg
  public/assets/img_badge.svg
  public/assets/main-panda.svg
  public/fonts/PretendardVariable.woff2
  styles/bulletinBoard.module.css
  styles/bulletinBoardAll.module.css
  styles/bulletinBoardBest.module.css
  styles/globals.css
  styles/header.module.css
  styles/main.module.css
  tsconfig.json
  utils/fetchData.ts
Labels: 미완성🫠, 순한맛🐑, 진행 중 🏃

#123 [이동혁] sprint8
  .gitignore
  components/Article.tsx
  components/BestArticle.tsx
  components/Comment.tsx
  components/Footer.tsx
  components/ServHeader.tsx
  components/ServLayout.tsx
  components/common/Button.tsx
  components/common/PaginationButton.tsx
  eslint.config.mjs
  functions/refresh.ts
  functions/timeAgo.ts
  hooks/useDebounce.ts
  hooks/useWindowSize.ts
  next.config.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/board/edit/[id].tsx
  pages/board/index.tsx
  pages/board/post/[id].tsx
  pages/board/write.tsx
  pages/index.tsx
  pages/logintest.tsx
  pages/test.tsx
  postcss.config.mjs
  public/favicon.ico
  public/file.svg
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/globe.svg
  public/imgs/Img_reply_empty.png
  public/imgs/ic_back.png
  public/imgs/ic_facebook.png
  public/imgs/ic_heart.png
  public/imgs/ic_instagram.png
  public/imgs/ic_kebab.png
  public/imgs/ic_medal.png
  public/imgs/ic_profile.png
  public/imgs/ic_search.png
  public/imgs/ic_sort.png
  public/imgs/ic_twitter.png
  public/imgs/ic_youtube.png
  public/imgs/mobile_logo.png
  public/imgs/notebook.png
  public/imgs/panda_logo.png
  public/imgs/polygon.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  styles/globals.css
  tailwind.config.ts
  tsconfig.json
  types/ArticleCard.ts
  utils/axiosInstance.ts
Labels: 매운맛🔥, 최종 제출

#112 [가승연] Sprint 8
  .gitignore
  assets/Frame2609463.png
  assets/Group 19.png
  assets/Group.png
  assets/facebook.png
  assets/instagram.png
  assets/twitter.png
  assets/로그인.png
  context/ArticleContext.js
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/api/articles.js
  pages/articles/[id].js
  pages/articles/index.js
  pages/articles/new.js
  pages/components/ArticleDetail.js
  pages/components/BesstArticle.js
  pages/components/DropDown.js
  pages/components/Nav.js
  pages/components/articleDropDown.js
  pages/components/articleList.js
  pages/components/commentsList.js
  pages/components/footer.js
  pages/index.js
  postcss.config.mjs
  public/Img_reply_empty.png
  public/Vector (1).png
  public/btn_sort.png
  public/colorheart.png
  public/heart.png
  public/ic_back.png
  public/ic_kebab.png
  public/ic_sort.png
  public/img_badge (1).png
  public/img_badge.png
  public/mediumHeart.png
  public/next.svg
  public/profilenone.png
  public/small_heart.png
  public/smallprofile.png
  public/vercel.svg
  public/window.svg
  styles/globals.css
  tailwind.config.mjs
Labels: 매운맛🔥, 최종 제출

#125 [박세정] sprint8
  mission8-fe/.gitignore
  mission8-fe/README.md
  mission8-fe/eslint.config.mjs
  mission8-fe/global/components/CustomDropdown.tsx
  mission8-fe/global/components/useInfiniteScroll.tsx
  mission8-fe/global/footer/Footer.tsx
  mission8-fe/global/header/Header.tsx
  mission8-fe/next.config.ts
  mission8-fe/output.css
  mission8-fe/package-lock.json
  mission8-fe/package.json
  mission8-fe/pages/_app.tsx
  mission8-fe/pages/_document.tsx
  mission8-fe/pages/article/[id].tsx
  mission8-fe/pages/freeboard.tsx
  mission8-fe/pages/index.tsx
  mission8-fe/pages/market.tsx
  mission8-fe/pages/write-article/[id].tsx
  mission8-fe/pages/write-article/new.tsx
  mission8-fe/postcss.config.mjs
  mission8-fe/public/assets/Group 19.png
  mission8-fe/public/assets/Img_reply_empty.png
  mission8-fe/public/assets/ic_arrow_down.png
  mission8-fe/public/assets/ic_back.png
  mission8-fe/public/assets/ic_facebook.png
  mission8-fe/public/assets/ic_heart.png
  mission8-fe/public/assets/ic_instagram.png
  mission8-fe/public/assets/ic_kebab.png
  mission8-fe/public/assets/ic_profile.png
  mission8-fe/public/assets/ic_search.png
  mission8-fe/public/assets/ic_sort.png
  mission8-fe/public/assets/ic_twitter.png
  mission8-fe/public/assets/ic_youtube.png
  mission8-fe/public/assets/img_badge.png
  mission8-fe/public/assets/img_default.png
  mission8-fe/public/file.svg
  mission8-fe/public/globe.svg
  mission8-fe/public/next.svg
  mission8-fe/public/vercel.svg
  mission8-fe/public/window.svg
  mission8-fe/styles/fonts/PretendardVariable.woff2
  mission8-fe/styles/global.css
  mission8-fe/tailwind.config.ts
  mission8-fe/tsconfig.json
Labels: 순한맛🐑, 최종 제출

#113 [정한샘] Spring 8
  .gitignore
  README.md
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.js
  public/btn_medium.png
  public/home_logo.png
  public/home_logo_text.png
  public/ic_badge.png
  public/ic_facebook.png
  public/ic_heart.png
  public/ic_instagram.png
  public/ic_kebab.png
  public/ic_profile.png
  public/ic_search.png
  public/ic_toggle.png
  public/ic_twitter.png
  public/ic_youtube.png
  public/img_default.png
  public/img_reply_empty.png
  public/logo.png
  src/components/BestPostCard.js
  src/components/CommentItem.js
  src/components/Container.js
  src/components/Footer.js
  src/components/GeneralPostList.js
  src/components/Header.js
  src/components/Select.js
  src/hooks/useCustomMediaQuery.js
  src/lib/axios.js
  src/pages/_app.js
  src/pages/_document.js
  src/pages/community/[id]/index.js
  src/pages/community/index.js
  src/pages/community/write/[id].js
  src/pages/community/write/index.js
  src/pages/index.js
  src/pages/market/index.js
  src/styles/globals.css
  tailwind.config.js
Labels: 매운맛🔥, 최종 제출

#131 [윤민호] sprint9
  components/ArticlePage.tsx
  components/ArticleSell.tsx
  components/BulletinBoardAll.tsx
  components/BulletinBoardBest.tsx
  components/Header.tsx
  components/footer.tsx
  components/head.tsx
  core/apiClient.ts
  core/bulletinBoardApiService.ts
  core/commentApiService.ts
  core/itemsApiService.ts
  hooks/useInputValidation.ts
  hooks/useTogglePassword.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/bulletin-board/index.tsx
  pages/edit/[id].tsx
  pages/index.tsx
  pages/items/index.tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  pages/write/index.tsx
  public/assets/ic_google.svg
  public/assets/ic_kakao.svg
  public/assets/login_logo.svg
  public/assets/pw-img-off.svg
  public/assets/pw-img-on.svg
  styles/articlePage.module.css
  styles/articleSell.module.css
  styles/globals.css
  styles/items.module.css
  styles/login.module.css
  styles/main.module.css
  styles/signup.module.css
  tsconfig.json
  utils/fetchData.ts
  utils/formValidation.ts
Labels: 매운맛🔥, 미완성🫠, 진행 중 🏃

#127 [가승연] Sprint 9
  context/AuthContext.js
  context/ProductContext.js
  package-lock.json
  package.json
  pages/_app.js
  pages/api/articles.js
  pages/api/articles.jsx
  pages/api/products.jsx
  pages/api/user.jsx
  pages/articles/ArticleDetail.jsx
  pages/articles/ArticleList.jsx
  pages/articles/BesstArticle.jsx
  pages/articles/[id].js
  pages/articles/[id].jsx
  pages/articles/index.jsx
  pages/articles/new.jsx
  pages/components/ArticleCommentsList.jsx
  pages/components/ArticleDropDown.jsx
  pages/components/DropDown.jsx
  pages/components/Footer.jsx
  pages/components/Nav.js
  pages/components/Nav.jsx
  pages/components/ProductCommentList.jsx
  pages/components/articleList.js
  pages/components/relativeTime.jsx
  pages/login/index.jsx
  pages/products/BestProducts.jsx
  pages/products/ProductDetail.jsx
  pages/products/ProductsList.jsx
  pages/products/[id].jsx
  pages/products/index.jsx
  pages/products/new.jsx
  pages/signup/index.jsx
  public/Img_home_bottom.png
  public/Img_home_top.png
  public/Vector 27.png
  public/arrow_left.png
  public/arrow_right.png
  public/colorheartIcon.png
  public/eye.png
  public/goggle.png
  public/img_default.png
  public/kakao.png
  public/loginpandalogo.png
  public/secret.png
  public/서치.png
  public/인기상품.png
  public/판다마켓.png
Labels: 매운맛🔥, 최종 제출

#132 [정한샘] Spring 9
  next.config.mjs
  package-lock.json
  package.json
  public/btn_visibility_off.png
  public/btn_visibility_on.png
  public/home_logo.png
  public/ic_X.png
  public/ic_google.png
  public/ic_heart_fill.png
  public/ic_kakao.png
  public/img_inquiry_empty.png
  src/components/CommentItem.js
  src/components/GeneralPostList.js
  src/components/Header.js
  src/components/Modal.js
  src/contexts/AuthProvider.js
  src/hooks/useLocalStorage.js
  src/lib/axios.js
  src/pages/_app.js
  src/pages/community/write/index.js
  src/pages/items/[id]/index.js
  src/pages/items/index.js
  src/pages/items/write/[id].js
  src/pages/items/write/index.js
  src/pages/login/index.js
  src/pages/market/index.js
  src/pages/signup/index.js
Labels: 매운맛🔥, 최종 제출
