Repository codeit-sprint-fullstack/5-sprint-mission-fe, pull requests merged in 2025-01, with the labels that each got.

#29 [정한샘] sprint3
  faq/index.html
  index.html
  items/index.html
  js/authUtils.js
  js/localstorage.js
  js/login.js
  js/signup.js
  login/index.html
  login/style.css
  privacy/index.html
  signup/index.html
  signup/style.css
  style.css
Labels: 매운맛🔥, 최종 제출

#36 [민지영] sprint3
  mission03/css/index-style.css
  mission03/css/modal.css
  mission03/css/reset.css
  mission03/css/style.css
  mission03/data/USER_DATA.js
  mission03/feature/auth/verifyAuth.js
  mission03/feature/modal/modalHandler.js
  mission03/feature/toggle/toggleIcon.js
  mission03/feature/valid/condition.js
  mission03/feature/valid/handler.js
  mission03/feature/valid/setError.js
  mission03/feature/valid/verifyForm.js
  mission03/html/faq.html
  mission03/html/items.html
  mission03/html/login.html
  mission03/html/privacy-policy.html
  mission03/html/signup.html
  mission03/img/Img_home_bottom.png
  mission03/img/Img_home_landing.png
  mission03/img/Img_hot-item.png
  mission03/img/Img_register.png
  mission03/img/Img_search.png
  mission03/img/btn_visibility_off.png
  mission03/img/btn_visibility_on.png
  mission03/img/google.png
  mission03/img/ic_facebook.png
  mission03/img/ic_instagram.png
  mission03/img/ic_twitter.png
  mission03/img/ic_youtube.png
  mission03/img/ico.png
  mission03/img/kakao.png
  mission03/img/logo.png
  mission03/index.html
Labels: 매운맛🔥, 최종 제출

#37 [김희성] sprint 3
  index.HTML
  index.css
  login.css
  login.html
  login.js
  signup.css
  signup.html
  signup.js
Labels: 매운맛🔥, 최종 제출

#39 [윤민호] sprint3
  .vscode/settings.json
  faq/index.html
  img/img_panda_mobile.png
  index.css
  index.html
  item/index.html
  js/public.js
  login/img/pw-img-off.png
  login/img/pw-img-on.png
  login/index.css
  login/index.html
  login/index.js
  login/login.html
  privacy/index.html
  signup/img/pw-img-off.png
  signup/img/pw-img-on.png
  signup/index.css
  signup/index.html
  signup/index.js
  signup/signup.html
Labels: 순한맛🐑, 최종 제출

#40 [최은비] sprint3
  btn_visibility_off.svg
  btn_visibility_on_24px.svg
  eye-btn.png
  google_icn.png
  index.html
  items.html
  js.css
  js/buttonToggle.js
  js/eventListener.js
  js/login.js
  js/modal.js
  js/signup.js
  js/userDatabase.js
  js/validate.js
  kakao_icn.png
  login.html
  loginstyle.css
  signup.html
  signupstyle.css
  style.css
Labels: 매운맛🔥, 최종 제출

#52 [박세정] Sprint3
  .vscode/settings.json
  Frame 2608833.png
  Group 19.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  faq/index.html
  ic_facebook.png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.css
  index.html
  items/items.html
  login/Component 2@3x.png
  login/Component 3@3x.png
  login/btn_visibility_off_24px.png
  login/btn_visibility_on_24px.png
  login/login.css
  login/login.html
  login/login.js
  login/logo.png
  login/reset.css
  login/signup.css
  login/signup.html
  login/signup.js
  privacy/index.html
  reset.css
Labels: 순한맛🐑, 최종 제출

#33 [유호은] sprint3
  README.md
  assets/btn_visibility_off.svg
  assets/btn_visibility_on.svg
  assets/logo_icon.png
  assets/logo_text.png
  index.html
  js/controlUI.js
  js/index.js
  js/login.js
  js/signup.js
  js/userDataList.js
  js/verifyAuth.js
  login.html
  signup.html
  style.css
  styles/auth.css
  styles/color.css
  styles/login.css
  styles/signup.css
  styles/style.css
Labels: 매운맛🔥, 최종 제출

#34 [이동혁] sprint3
  mission03/css/accountStyle.css
  mission03/css/mainStyle.css
  mission03/img/btn_caliber.png
  mission03/img/btn_login.png
  mission03/img/google_login.png
  mission03/img/ic_facebook.png
  mission03/img/ic_instagram.png
  mission03/img/ic_twitter.png
  mission03/img/ic_youtube.png
  mission03/img/kakao_login.png
  mission03/img/logo.png
  mission03/img/main_section_bottom.png
  mission03/img/main_section_top.png
  mission03/img/panda.ico
  mission03/img/serv_section_first.png
  mission03/img/serv_section_second.png
  mission03/img/serv_section_third.png
  mission03/img/small_logo.png
  mission03/img/vector.png
  mission03/img/vector_hide.png
  mission03/index.html
  mission03/js/accountCommon.js
  mission03/js/index.js
  mission03/js/login.js
  mission03/js/register.js
  mission03/login.html
  mission03/signup.html
Labels: 매운맛🔥, 최종 제출

#61 [신진호] SPRINT 4
  .idea/aws.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/material_theme_project_new.xml
  README.md
  SPRINT4/global.js
  SPRINT4/main.js
  SPRINT4/modules/ArticleService.js
  SPRINT4/modules/ProductService.js
  SPRINT4/thinkAbout.js
Labels: 매운맛🔥, 최종 제출

#28 [김조순] sprint3
  index.html
  js/login.js
  js/main.js
  js/signup.js
  pages/fqa.html
  pages/items.html
  pages/login.html
  pages/main.html
  pages/privacy.html
  pages/signup.html
  style/login.css
  style/main.css
Labels: 매운맛🔥, 최종 제출

#32 [정하윤] sprint3
  mission01+02.ver2/login.css
  mission01+02.ver2/login.html
  mission01+02.ver2/signup.css
  mission01+02.ver2/signup.html
  mission03/.DS_Store
  mission03/.vscode/settings.json
  mission03/api/ArticleService.js
  mission03/api/ProductService.js
  mission03/faq.html
  mission03/images/home/bottom-banner-image.png
  mission03/images/home/feature1-image.png
  mission03/images/home/feature2-image.png
  mission03/images/home/feature3-image.png
  mission03/images/home/hero-image.png
  mission03/images/icons/eye-invisible.svg
  mission03/images/icons/eye-visible.svg
  mission03/images/logo/favicon.ico
  mission03/images/logo/logo.svg
  mission03/images/social/facebook-logo.svg
  mission03/images/social/google-logo.png
  mission03/images/social/instagram-logo.svg
  mission03/images/social/kakao-logo.png
  mission03/images/social/twitter-logo.svg
  mission03/images/social/youtube-logo.svg
  mission03/index.html
  mission03/items.html
  mission03/login.html
  mission03/login.js
  mission03/main.js
  mission03/needtodo.txt
  mission03/privacy.html
  mission03/signup.html
  mission03/styles/auth.css
  mission03/styles/global.css
  mission03/styles/home.css
Labels: 매운맛🔥, 최종 제출

#45 [최유리] sprint3
  event.js
  event2.js
  login.html
  signup.html
  style.css
Labels: 매운맛🔥, 진행 중 🏃

#54 [최수빈] sprint3
  .DS_Store
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  FAQ.html
  README.md
  img/.DS_Store
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom-1.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/google.png
  img/ic_facebook.png
  img/ic_instagram.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/kakaotalk.png
  img/logo.png
  index.html
  items.html
  login-js.js
  login-style.css
  login.html
  login_style.css
  privacy.html
  reset.css
  signup-js.js
  signup.html
  singup-style.css
  singup_style.css
  style.css
Labels: 매운맛🔥, 미완성🫠, 진행 중 🏃

#71 [김승우] sprint4
  APIs/ApiService.js
  APIs/ArticleService.js
  APIs/ProductService.js
  APIs/main.js
Labels: 매운맛🔥, 최종 제출

#58 [정한샘] sprint4
  .gitignore
  api/ArticleService.js
  api/ProductService.js
  api/axiosInstance.js
  handlers/authUtils.js
  handlers/localstorage.js
  handlers/login.js
  handlers/main.js
  handlers/signup.js
  package-lock.json
  package.json
Labels: 매운맛🔥, 최종 제출

#62 [봉재완] sprint4
  mission4/.gitignore
  mission4/API/ArticleService.js
  mission4/API/ProductService.js
  mission4/API/main.js
  mission4/Panda.css
  mission4/img/Component 2.png
  mission4/img/Component 3.png
  mission4/img/Frame 2608833.png
  mission4/img/Img_home_02.png
  mission4/img/Img_home_03.png
  mission4/img/Img_home_bottom.png
  mission4/img/Img_home_top.png
  mission4/img/Vector-open.png
  mission4/img/Vector.png
  mission4/img/ic_facebook.png
  mission4/img/ic_instagram.png
  mission4/img/ic_twitter.png
  mission4/img/ic_youtube.png
  mission4/img/login-logo.png
  mission4/img/logo.png
  mission4/index.html
  mission4/items/items.html
  mission4/login/index.html
  mission4/login/index.js
  mission4/login/style.css
  mission4/package-lock.json
  mission4/package.json
  mission4/signup/index.html
  mission4/signup/index.js
  mission4/signup/style.css
Labels: 매운맛🔥, 최종 제출

#72 [최수빈] mission 4
  4th/article.js
  4th/main.js
  4th/package.json
  4th/products.js
Labels: 매운맛🔥, 최종 제출

#77 [신진호] sprint 5
  .gitignore
  build/asset-manifest.json
  build/favicon.ico
  build/index.html
  build/logo192.png
  build/logo512.png
  build/manifest.json
  build/placeholder.png
  build/robots.txt
  build/static/css/main.3cca87ff.css
  build/static/css/main.3cca87ff.css.map
  build/static/js/488.40d4a970.chunk.js
  build/static/js/488.40d4a970.chunk.js.map
  build/static/js/main.4b47702d.js
  build/static/js/main.4b47702d.js.LICENSE.txt
  build/static/js/main.4b47702d.js.map
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/placeholder.png
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/images/facebook.png
  src/assets/images/icon.png
  src/assets/images/insta.png
  src/assets/images/logo.png
  src/assets/images/placeholder.png
  src/assets/images/titleonly.png
  src/assets/images/twitter.png
  src/assets/images/youtube.png
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/setupTests.js
  src/shared/hooks/useWindowWidth.js
  src/widgets/Content/BestProducts/BestProduct.jsx
  src/widgets/Content/Content.jsx
  src/widgets/Content/OnSaleProduct/OnSaleProduct.jsx
  src/widgets/Content/OnSaleProduct/OnSaleProductNav.jsx
  src/widgets/Content/OnSaleProduct/PageClickButton.jsx
  src/widgets/Content/ProductList/ProductList.jsx
  src/widgets/Footer/Footer.jsx
  src/widgets/Header/Header.jsx
  tailwind.config.js
Labels: 매운맛🔥, 최종 제출

#79 [김희성] sprint 5
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.jsx
  src/api/Productapi.jsx
  src/components/bestProduct/bestproduct.jsx
  src/components/bestProduct/img/Like_Icon.png
  src/components/footer/footer.jsx
  src/components/footer/img/InstaG.png
  src/components/footer/img/Twitter.png
  src/components/footer/img/Youtube.png
  src/components/footer/img/facebook.png
  src/components/footer/img/판다 얼굴.png
  src/components/footer/img/판다마켓.png
  src/components/header/header.jsx
  src/components/header/img/판다 얼굴.png
  src/components/header/img/판다마켓.png
  src/components/onSaleProduct/customselect/costomselect.jsx
  src/components/onSaleProduct/customselect/img/ic_arrow_down.png
  src/components/onSaleProduct/customselect/img/ic_sort.png
  src/components/onSaleProduct/img/Like_Icon.png
  src/components/onSaleProduct/onSaleProduct.jsx
  src/components/pagination/img/btn_left.png
  src/components/pagination/img/btn_right.png
  src/components/pagination/pagination.jsx
  src/index.js
Labels: 매운맛🔥, 최종 제출

#81 [김민희] sprint5
  react-project/.gitignore
  react-project/README.md
  react-project/package-lock.json
  react-project/package.json
  react-project/public/favicon.ico
  react-project/public/index.html
  react-project/public/manifest.json
  react-project/public/robots.txt
  react-project/src/App.css
  react-project/src/App.jsx
  react-project/src/assets/icons/arrow_down.png
  react-project/src/assets/icons/basic_user_profile.png
  react-project/src/assets/icons/product_card_heart.png
  react-project/src/assets/icons/search_ic.png
  react-project/src/assets/icons/sns/facebook.png
  react-project/src/assets/icons/sns/instagram.png
  react-project/src/assets/icons/sns/twitter.png
  react-project/src/assets/icons/sns/youtube.png
  react-project/src/assets/icons/sort.png
  react-project/src/assets/imgs/logos/image_logo.png
  react-project/src/assets/imgs/logos/logo.png
  react-project/src/assets/imgs/logos/logo2.png
  react-project/src/assets/imgs/logos/text_logo.png
  react-project/src/assets/imgs/product_no_img.png
  react-project/src/components/Dropdown/Dropdown.css
  react-project/src/components/Dropdown/Dropdown.jsx
  react-project/src/components/FooterSection/FooterSection.css
  react-project/src/components/FooterSection/FooterSection.jsx
  react-project/src/components/Input/SearchInput/SearchInput.css
  react-project/src/components/Input/SearchInput/SearchInput.jsx
  react-project/src/components/NavSection/NavSection.css
  react-project/src/components/NavSection/NavSection.jsx
  react-project/src/components/ProductCard/ProductCard.css
  react-project/src/components/ProductCard/ProductCard.jsx
  react-project/src/components/button/PrimaryButton/PrimaryButton.jsx
  react-project/src/components/button/pagination/PageButton/PageButton.css
  react-project/src/components/button/pagination/PageButton/PageButton.jsx
  react-project/src/components/button/pagination/PageGroupChangeButton/PageGroupChangeButton.css
  react-project/src/components/button/pagination/PageGroupChangeButton/PageGroupChangeButton.jsx
  react-project/src/hooks/useScreenType.jsx
  react-project/src/index.js
  react-project/src/pages/MarketPlacePage/MarketPlacePage.css
  react-project/src/pages/MarketPlacePage/MarketPlacePage.jsx
  react-project/src/pages/MarketPlacePage/section/BestProductsList/BestProductsList.css
  react-project/src/pages/MarketPlacePage/section/BestProductsList/BestProductsList.jsx
  react-project/src/pages/MarketPlacePage/section/ProductsList/ProductsList.css
  react-project/src/pages/MarketPlacePage/section/ProductsList/ProductsList.jsx
  react-project/src/services/ProductService.js
  react-project/src/styles/color.css
  react-project/src/styles/font.css
  react-project/src/styles/reset.css
Labels: 순한맛🐑, 최종 제출

#83 [민지영] sprint5
  README.md
  mission05-tailwind/.gitignore
  mission05-tailwind/README.md
  mission05-tailwind/eslint.config.js
  mission05-tailwind/index.html
  mission05-tailwind/package-lock.json
  mission05-tailwind/package.json
  mission05-tailwind/postcss.config.js
  mission05-tailwind/public/favicon.png
  mission05-tailwind/src/App.jsx
  mission05-tailwind/src/ItemsPage/components/Pagination/index.jsx
  mission05-tailwind/src/ItemsPage/components/PaginationItem/index.jsx
  mission05-tailwind/src/ItemsPage/components/Product/index.jsx
  mission05-tailwind/src/ItemsPage/components/ProductLikes/index.jsx
  mission05-tailwind/src/ItemsPage/components/ProductSkeleton/index.jsx
  mission05-tailwind/src/ItemsPage/index.jsx
  mission05-tailwind/src/ItemsPage/layouts/ProductForBest/index.jsx
  mission05-tailwind/src/ItemsPage/layouts/ProductForSale/index.jsx
  mission05-tailwind/src/apis/productService.js
  mission05-tailwind/src/apis/service.js
  mission05-tailwind/src/apis/setAxiosDefault.js
  mission05-tailwind/src/assets/filter/ic_arrow_down.png
  mission05-tailwind/src/assets/filter/ic_sort.png
  mission05-tailwind/src/assets/likes/ic_heart.png
  mission05-tailwind/src/assets/logo/logo-img.png
  mission05-tailwind/src/assets/logo/logo-title.png
  mission05-tailwind/src/assets/pagination/arrow_left.png
  mission05-tailwind/src/assets/product/img_default.png
  mission05-tailwind/src/assets/search/ic_search.png
  mission05-tailwind/src/assets/sns/ic_facebook.png
  mission05-tailwind/src/assets/sns/ic_instagram.png
  mission05-tailwind/src/assets/sns/ic_twitter.png
  mission05-tailwind/src/assets/sns/ic_youtube.png
  mission05-tailwind/src/common/components/Button/index.jsx
  mission05-tailwind/src/common/components/ProductFilter/index.jsx
  mission05-tailwind/src/common/components/ProductSearch/index.jsx
  mission05-tailwind/src/common/hooks/useDebounce.js
  mission05-tailwind/src/common/hooks/useDeviceType.js
  mission05-tailwind/src/common/hooks/useFetch.js
  mission05-tailwind/src/common/layouts/Footer/index.jsx
  mission05-tailwind/src/common/layouts/Header-2/index.jsx
  mission05-tailwind/src/css/all-unset.css
  mission05-tailwind/src/index.css
  mission05-tailwind/src/main.jsx
  mission05-tailwind/tailwind.config.js
  mission05-tailwind/vite.config.js
Labels: 매운맛🔥, 최종 제출

#86 [김승우] Sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  postcss.config.js
  public/index.html
  src/App.js
  src/Footer.js
  src/apis/apiClient.js
  src/apis/productService.js
  src/assets/logo.png
  src/bestproduct/BestProducts.js
  src/bestproduct/ProductCard.js
  src/index.css
  src/index.js
  src/navbar/Navbar.js
  src/navbar/components/LoginButton.js
  src/navbar/components/Logo.js
  src/navbar/components/Menu.js
  src/productList/Pagination.js
  src/productList/ProductList.js
  tailwind.config.js
Labels: 매운맛🔥, 최종 제출

#84 [정하윤] sprint5
  mission-fe/.gitignore
  mission-fe/README.md
  mission-fe/package-lock.json
  mission-fe/package.json
  mission-fe/public/index.html
  mission-fe/src/App.js
  mission-fe/src/assets/icons/Avatar.png
  mission-fe/src/assets/icons/Vector.png
  mission-fe/src/assets/icons/btn_sort.png
  mission-fe/src/assets/icons/eye-invisible.svg
  mission-fe/src/assets/icons/eye-visible.svg
  mission-fe/src/assets/icons/ic_arrow_down.png
  mission-fe/src/assets/icons/ic_heart.png
  mission-fe/src/assets/icons/img_default.png
  mission-fe/src/assets/images/home/bottom-banner-image.png
  mission-fe/src/assets/images/home/feature1-image.png
  mission-fe/src/assets/images/home/feature2-image.png
  mission-fe/src/assets/images/home/feature3-image.png
  mission-fe/src/assets/images/home/hero-image.png
  mission-fe/src/assets/images/logo/favicon.ico
  mission-fe/src/assets/images/logo/headerlogo_mobile.png
  mission-fe/src/assets/images/logo/logo.svg
  mission-fe/src/assets/images/social/facebook-logo.svg
  mission-fe/src/assets/images/social/google-logo.png
  mission-fe/src/assets/images/social/instagram-logo.svg
  mission-fe/src/assets/images/social/kakao-logo.png
  mission-fe/src/assets/images/social/twitter-logo.svg
  mission-fe/src/assets/images/social/youtube-logo.svg
  mission-fe/src/components/common/DropDown.jsx
  mission-fe/src/components/common/NavMenu.css
  mission-fe/src/components/common/NavMenu.jsx
  mission-fe/src/components/common/Pagination.css
  mission-fe/src/components/common/Pagination.jsx
  mission-fe/src/components/common/SearchInput.jsx
  mission-fe/src/components/features/products/BestItems.css
  mission-fe/src/components/features/products/BestItems.jsx
  mission-fe/src/components/features/products/OnSaleItems.css
  mission-fe/src/components/features/products/OnSaleItems.jsx
  mission-fe/src/components/features/products/auth/.gitkeep
  mission-fe/src/components/layout/Footer.css
  mission-fe/src/components/layout/Footer.jsx
  mission-fe/src/components/layout/Header.css
  mission-fe/src/components/layout/Header.jsx
  mission-fe/src/hooks/useResponsivePageSize.js
  mission-fe/src/index.js
  mission-fe/src/styles/App.css
  mission-fe/src/styles/global.css
Labels: 순한맛🐑, 최종 제출

#91 [최은비] sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  public/pandaIcon.png
  src/App.jsx
  src/assets/font/PretendardVariable.woff2
  src/assets/img/arrow_left.png
  src/assets/img/arrow_right.png
  src/assets/img/ic_arrow_down.png
  src/assets/img/ic_facebook.png
  src/assets/img/ic_instagram.png
  src/assets/img/ic_search.png
  src/assets/img/ic_sort.png
  src/assets/img/ic_twitter.png
  src/assets/img/ic_youtube.png
  src/assets/img/img_default.png
  src/assets/img/like.png
  src/assets/img/logo1.png
  src/assets/img/usercon.png
  src/common/Footer.js
  src/common/Header.js
  src/common/SearchBar.jsx
  src/components/Filter/index.jsx
  src/components/SalesItems/ItemCard.js
  src/components/SalesItems/ItemList.js
  src/components/bestItems/BestItemCard.js
  src/components/bestItems/BestItemList.js
  src/components/feature/GetItemsApi.js
  src/components/feature/Pagination.jsx
  src/components/feature/SetOrder.jsx
  src/index.css
  src/index.js
  src/output.css
  tailwind.config.js
Labels: 매운맛🔥, 최종 제출

#82 [유호은] sprint5
  sprint-mission/.gitignore
  sprint-mission/README.md
  sprint-mission/package-lock.json
  sprint-mission/package.json
  sprint-mission/public/index.html
  sprint-mission/public/logo_favicon.ico
  sprint-mission/src/App.js
  sprint-mission/src/index.css
  sprint-mission/src/index.js
  sprint-mission/src/pages/ItemsPage/ItemsPage.css
  sprint-mission/src/pages/ItemsPage/ItemsPage.jsx
  sprint-mission/src/pages/ItemsPage/ItemsPageLayout.jsx
  sprint-mission/src/pages/ItemsPage/section/BestItems/BestItems.css
  sprint-mission/src/pages/ItemsPage/section/BestItems/BestItems.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/OnSaleItems.css
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/OnSaleItems.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/hooks/useOrderBy.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/hooks/usePagination.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/ui/PaginationItems.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/ui/PostItems.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/ui/SearchItems.jsx
  sprint-mission/src/pages/ItemsPage/section/OnSaleItems/ui/SortItems.jsx
  sprint-mission/src/pages/ItemsPage/section/hooks/useItemsFetch.jsx
  sprint-mission/src/pages/ItemsPage/section/ui/ItemCard.jsx
  sprint-mission/src/pages/ItemsPage/section/ui/SkeletonCard.jsx
  sprint-mission/src/shared/Footer/Footer.css
  sprint-mission/src/shared/Footer/Footer.jsx
  sprint-mission/src/shared/Footer/ui/FooterLink.jsx
  sprint-mission/src/shared/Footer/ui/FooterSns.jsx
  sprint-mission/src/shared/Header/Header.css
  sprint-mission/src/shared/Header/Header.jsx
  sprint-mission/src/shared/Header/ui/HeaderLink.jsx
  sprint-mission/src/shared/Header/ui/HeaderLogo.jsx
  sprint-mission/src/shared/Header/ui/HeaderUser.jsx
  sprint-mission/src/shared/Typo/Typo.css
  sprint-mission/src/shared/Typo/Typo.jsx
  sprint-mission/src/shared/assets/arrow_left.png
  sprint-mission/src/shared/assets/arrow_right.png
  sprint-mission/src/shared/assets/default_item.png
  sprint-mission/src/shared/assets/default_profile.png
  sprint-mission/src/shared/assets/facebook_icon.png
  sprint-mission/src/shared/assets/favorite_heart.png
  sprint-mission/src/shared/assets/insta_icon.png
  sprint-mission/src/shared/assets/logo_icon.png
  sprint-mission/src/shared/assets/logo_img.png
  sprint-mission/src/shared/assets/logo_text.png
  sprint-mission/src/shared/assets/mobile_sort_icon.png
  sprint-mission/src/shared/assets/search_icon.png
  sprint-mission/src/shared/assets/sort_icon.png
  sprint-mission/src/shared/assets/twitter_icon.png
  sprint-mission/src/shared/assets/youtube_icon.png
  sprint-mission/src/shared/store/useScreenSizeStore.jsx
  sprint-mission/src/shared/styles/color.css
  sprint-mission/src/shared/styles/reset.css
  sprint-mission/src/shared/ui/CardImg.jsx
  sprint-mission/src/shared/ui/RouteLayout.jsx
  sprint-mission/src/utils/APIs/axiosInstance.js
  sprint-mission/src/utils/APIs/getItemsListAPI.js
  sprint-mission/src/utils/constants.js
Labels: 매운맛🔥, 최종 제출

#88 [봉재완] sprint 5
  README.md
  mission5/.gitignore
  mission5/package-lock.json
  mission5/package.json
  mission5/public/favicon.ico
  mission5/public/index.html
  mission5/public/logo192.png
  mission5/public/logo512.png
  mission5/public/manifest.json
  mission5/public/robots.txt
  mission5/src/App.js
  mission5/src/components/AddProduct.js
  mission5/src/components/Dropdown.js
  mission5/src/components/Footer.js
  mission5/src/components/Header.js
  mission5/src/components/ImageUploader.js
  mission5/src/components/Pagination.js
  mission5/src/components/ProductCard.js
  mission5/src/components/ProductList.js
  mission5/src/components/ProductManager.js
  mission5/src/components/SearchBar.js
  mission5/src/index.js
  mission5/src/styles/GlobalStyle.js
Labels: 매운맛🔥, 최종 제출

#92 [김조순] sprint5
  .gitignore
  README.md
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  public/ic_facebook.png
  public/ic_heart.png
  public/ic_instagram.png
  public/ic_login.png
  public/ic_search.png
  public/ic_sort.png
  public/ic_twitter.png
  public/ic_youtube.png
  public/logo_icon.png
  public/no_image.png
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.module.css
  src/app/page.tsx
  src/app/store/api/api.tsx
  src/app/store/componants/BestGoodsGrid.tsx
  src/app/store/componants/BestGoodsItem.tsx
  src/app/store/componants/FilterOption.tsx
  src/app/store/componants/Footer.tsx
  src/app/store/componants/GoodsGrid.tsx
  src/app/store/componants/GoodsItem.tsx
  src/app/store/componants/Header.tsx
  src/app/store/componants/Layout.tsx
  src/app/store/componants/PageNation.tsx
  src/app/store/hook/hook.tsx
  src/app/store/page.tsx
  src/components/ui/avatar.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/close-button.tsx
  src/components/ui/color-mode.tsx
  src/components/ui/dialog.tsx
  src/components/ui/drawer.tsx
  src/components/ui/field.tsx
  src/components/ui/input-group.tsx
  src/components/ui/link-button.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/components/ui/provider.tsx
  src/components/ui/radio.tsx
  src/components/ui/select.tsx
  src/components/ui/slider.tsx
  src/components/ui/tooltip.tsx
  tsconfig.json
Labels: 매운맛🔥, 최종 제출

#98 [김희성] sprint 6
  package-lock.json
  package.json
  src/App.jsx
  src/api/Productapi.jsx
  src/components/Share/InputField.jsx
  src/components/Share/footer/footer.jsx
  src/components/Share/pagination.jsx
  src/components/footer/footer.jsx
  src/components/header/header.jsx
  src/components/header/img/판다 얼굴.png
  src/components/header/img/판다마켓.png
  src/components/img/InstaG.png
  src/components/img/Like_Icon.png
  src/components/img/TopBannerImg.png
  src/components/img/Twitter.png
  src/components/img/X-round-Icon.png.png
  src/components/img/Youtube.png
  src/components/img/baseImg.png
  src/components/img/bottomBannerImg.png
  src/components/img/btn_left.png
  src/components/img/btn_right.png
  src/components/img/facebook.png
  src/components/img/middleImg_01.png
  src/components/img/middleImg_02.png
  src/components/img/middleImg_03.png
  src/components/img/판다 얼굴.png
  src/components/img/판다마켓.png
  src/components/onSaleProduct/customselect/costomselect.jsx
  src/components/onSaleProduct/img/Like_Icon.png
  src/components/onSaleProduct/onSaleProduct.jsx
  src/index.css
  src/index.js
  src/page/bestProduct/BestProduct.jsx
  src/page/header/header.jsx
  src/page/itemsPage/ItemsPage.jsx
  src/page/main/main.jsx
  src/page/onSaleProduct/OnSaleProduct.jsx
  src/page/onSaleProduct/customselect/costomselect.jsx
  src/page/onSaleProduct/customselect/img/ic_arrow_down.png
  src/page/onSaleProduct/customselect/img/ic_sort.png
  src/page/productRegistration/ProductRegistration.jsx
  src/page/registrationPage/RegistrationPage.jsx
  src/page/registrationPage/Validation/Validation.jsx
  tailwind.config.js
Labels: 매운맛🔥, 최종 제출
